localIp: ~
gateway: ~
duration: 60m
refreshInterval: 15m
ports:
  - externalPort: 8080
    internalPort: 80
    protocol: TCP
    name: yaml-web
  - externalPort: 9000
    internalPort: 90
    protocol: UDP
    name: yaml-stream